#!/bin/sh

DIR=$(dirname $(realpath $0))

cd $DIR

exec setuidgid www /usr/local/bin/uwsgi \
    --socket=/tmp/muspy.sock \
    --pythonpath="$DIR" \
    --master \
    --processes=6 \
    --harakiri=30 \
    --max-requests=1000 \
    --env="DJANGO_SETTINGS_MODULE=settings" \
    --module="django.core.handlers.wsgi:WSGIHandler()"
