#!/bin/sh

# This script monitors other daemons and restarts them if they are dead.
# Add it to the crontab on @reboot.

trap 'kill $MB_PID; exit' HUP INT TERM

MB_PID=

while :
do
    if [ -z "$MB_PID" ] || ! kill -0 $MB_PID > /dev/null 2>&1 ; then
        ./musicbrainz.py &
        MB_PID="$!"
    fi

    sleep 10
done
