#!/bin/sh

# The daemon will exit after each fetch cycle, this script makes sure the daemon
# is restarted when it's done fetching or it's dead.
# Add this script to the crontab on @reboot.

trap 'kill $PID; exit' INT TERM

LOG=/tmp/muspy.log
PID=

while :
do
    if [ -z "$PID" ] || ! kill -0 $PID > /dev/null 2>&1 ; then
        $(dirname $0)/daemon.py >> $LOG 2>&1 &
        PID="$!"
    fi

    sleep 10
done
